### ISSUE TITLE
Not detecting drift in a struct within a nested slice

### ISSUE THREAD

**Issue by kurtmaile** [go-test/deep#17] opened 2018-04-17 15:18 UTC
Hi,

Ive started using this library its great!

I have been playing around testing this and works well.  We have some big JSON that gets marshalled into structs, ive found changing something fairly deeply nested wasnt being picked up.

So orderLines is a slice, it DOES pick up a change to a field in the top of the slice like Id

e.g OrderEvent.Order.OrderLines.slice[0].Id

but if its another struct within the slice, it doesnt pick this up, like 'Gross' below

e.g OrderEvent.Order.OrderLines.slice[0].UnitPrice.Gross (float64)

Is this a know thing?  Is there a limit how deep you can go?

Thanks!

**Comment by daniel-nichter** [comment] 2018-04-28 03:07
Hello @kurtmaile. Yes, there are two const: `MaxDiff` and `MaxDepth` (https://godoc.org/github.com/go-test/deep).  Perhaps these are the cause? If not, please provide some test data that reproduces the problem.

**Comment by daniel-nichter** [comment] 2019-07-14 21:05
If this can be reproduced in a test case, please submit a PR. Until then, closing this issue.

**Closed by daniel-nichter** 2019-07-14 21:05 UTC
